log:
  level: "INFO"

input:
  parameter_num: 3
  labels: ["A", "B"]

parameter_ranges:
  - [-10, 10]
  - [-10, 10]
  - [-10, 10]

bias_range: [-10, 10]

ga:
  max_generation: 100
  initialization:
    population_num: 50

  evaluation:
    opt_metric: "f_mesure"
    average_num: 10
    tolerance: 1.0E-4

  selection:
    parent_num: 25
    strategy: "elite"
    elite_ratio: 0.5

  crossover:
    crossover_pairs: 30
    prob: 0.8
    type: "BLX-alpha"
    alpha: 0.3

  mutation:
    prob: 0.01
    type: "uniform"
